### ISSUE TITLE
Can't link

### ISSUE THREAD

**Issue by thedevdavid** [BranchMetrics/react-native-branch-deep-linking-attribution#359]
1. Clean project with latest React Native.
2. `yarn add...`
3. `react-native link react-native-branch `
4. Created branch.json and branch.debug.json

Result:
```
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'android/app/src/debug/assets'
    at Object.fs.mkdirSync (fs.js:885:18)
    at ensureDirectory (/Users/davidlevai/Desktop/Learning/ReactNative/BranchPOC/node_modules/react-native-branch/scripts/androidUtil.js:98:8)
    at ensureAndroidAssetsFolder (/Users/davidlevai/Desktop/Learning/ReactNative/BranchPOC/node_modules/react-native-branch/scripts/androidUtil.js:81:3)
    at Object.addBranchConfigToAndroidAssetsFolder (/Users/davidlevai/Desktop/Learning/ReactNative/BranchPOC/node_modules/react-native-branch/scripts/androidUtil.js:26:5)
    at Object.<anonymous> (/Users/davidlevai/Desktop/Learning/ReactNative/BranchPOC/node_modules/react-native-branch/scripts/addBranchConfig.js:28:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
/Users/davidlevai/Desktop/Learning/ReactNative/BranchPOC/node_modules/react-native/local-cli/core/makeCommand.js:32
        throw new Error(`Error occurred during executing "${command}" command`);
        ^

Error: Error occurred during executing "node ./node_modules/react-native-branch/scripts/addBranchConfig.js" command
    at ChildProcess.prelink (/Users/davidlevai/Desktop/Learning/ReactNative/BranchPOC/node_modules/react-native/local-cli/core/makeCommand.js:32:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

![image](https://user-images.githubusercontent.com/15244882/43355598-5b2f9c20-925f-11e8-9b9a-6dd64d122704.png)

**Comment by sequoiaat** [comment]
@DLevai94 We followed your steps and were not able to reproduce this issue. Can you please share your project directory structure and the path where you placed the branch.json and branch.debug.json files?  Refer https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/branch.json.md for more information.

**Comment by DLevai94** [comment]
@sequoiaat it works great if I `cp node_modules/react-native-branch/branch.example.json branch.json` and not download this file: https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/branch.example.json

**Comment by skizzo** [comment]
I have the very same problem and don't quite know how to fix it. Using React Native `0.53.0` (and no, I can't upgrade to the latest RN version, the project is huge and it would break everything), node `v8.12.0` and get the same error message when running `react-native link react-native-branch` in the terminal. @DLevai94 's hint of copying the example JSON file didn't help either.

Is there a better solution for this? Thanks.

**Comment by trops** [comment]
Also getting same error
```
react-native-branch ERR! android/app/src/main/assets/branch.json is a link to ../../../../../branch.android.json. 
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir 'android/app/src/debug/assets'
```
