### ISSUE TITLE
Error while tracking events, "TypeError: u._newIdent is not a function "

### ISSUE THREAD

**Issue by anuragvijayvergia** [BranchMetrics/react-native-branch-deep-linking-attribution#630]
I am using following code to track events on branch. 

  **new BranchEvent(eventName, paramsObj).logEvent();** and **new BranchEvent(eventName).logEvent();**

My Branch SDK is throwing this error while tracking events. I am facing this issue on my production app.

TypeError: u._newIdent is not a function. (In 'u._newIdent()', 'u._newIdent' is undefined)
  at call(node_modules/react-native-branch/src/BranchEvent.js:156:17)
  at tryCatch(node_modules/regenerator-runtime/runtime.js:63:40)
  at call(node_modules/regenerator-runtime/runtime.js:293:22)
  at tryCatch(node_modules/regenerator-runtime/runtime.js:63:40)
  at invoke(node_modules/regenerator-runtime/runtime.js:154:20)
  at fn(node_modules/regenerator-runtime/runtime.js:166:13)
  at tryCallOne(node_modules/promise/setimmediate/core.js:37:12)
  at callback(node_modules/promise/setimmediate/core.js:123:15)
  at _callTimer(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:7)
  at _callImmediatesPass(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:181:5)
  at _immediatesCallback(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:441:12)
  at __callImmediates(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:387:12)
  at fn(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:12)
  at __guard(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:9)
  at value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:10)
  at value([native code])
  at value([native code])

If you have questions or issues integrating a Branch SDK, please email
support@branch.io. Thank you.

**Comment by abcdefghiraj** [comment]
Facing the same issue.

**Comment by hipages-ligang** [comment]
I encounter the same issue. I got "**TypeError: buo._newIdent is not a function**" in logEvent().catch()
`
branchEvent
            .logEvent()
            .then()
            .catch((error) => {
                console.log('-----' + error);
            });
`

**Comment by hipages-ligang** [comment]
I find out the root cause.
I use createBranchUniversalObject() to create BUO like this:
`const contentItem = branch.createBranchUniversalObject('identifier', branchUniversalObjectOptions);`
should add 'await' like this:
`const contentItem = await branch.createBranchUniversalObject('identifier', branchUniversalObjectOptions);`

**Comment by sandeepDevJs** [comment]
> I encounter the same issue. I got "**TypeError: buo._newIdent is not a function**" in logEvent().catch() `branchEvent .logEvent() .then() .catch((error) => { console.log('-----' + error); });`

did you find any work around?

**Comment by hiagolfMB** [comment]
> I find out the root cause. I use createBranchUniversalObject() to create BUO like this: `const contentItem = branch.createBranchUniversalObject('identifier', branchUniversalObjectOptions);` should add 'await' like this: `const contentItem = await branch.createBranchUniversalObject('identifier', branchUniversalObjectOptions);`


It worked for me. I used it as follows...
```
const contentItem = await branch.createBranchUniversalObject(eventName, eventParams)
const event = new BranchEvent(eventName, contentItem)
event.logEvent()
```

When you don't need to send parameters, just omit eventParams.
