### ISSUE TITLE
Android app crashes on start on 5.0.2 with liveKey / testKey / useTestInstance branch.json

### ISSUE THREAD

**Issue by saarim-otiswealth** [BranchMetrics/react-native-branch-deep-linking-attribution#643]
Upgraded from 5.0.1 to 5.0.2 and the android app keeps crashing as a result with the following output with the liveKey / testKey / useTestInstance format of branch.json:

```
2021-04-29 20:36:01.415 1686-1686/com.otiswealth.otis E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.otiswealth.otis, PID: 1686
    java.lang.RuntimeException: Unable to create application com.otiswealth.otis.MainApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6250)
        at android.app.ActivityThread.access$1200(ActivityThread.java:238)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1787)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at io.branch.referral.BranchJsonConfig.getBranchKey(BranchJsonConfig.java:123)
        at io.branch.referral.BranchUtil.readBranchKey(BranchUtil.java:90)
        at io.branch.referral.Branch.getAutoInstance(Branch.java:454)
        at io.branch.rnbranch.RNBranchModule.getAutoInstance(RNBranchModule.java:101)
        at com.otiswealth.otis.MainApplication.onCreate(MainApplication.java:71)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6245)
```

i switched over from using liveKey / testKey to using a single `branchKey`, which seems to have resolved the issue. have y'all dropped support for liveKey / testKey?

my `react-native info` result:

```
System:
    OS: macOS Mojave 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz
    Memory: 68.47 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.4.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.15 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/saarim/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_211 - /usr/bin/javac
    Python: 3.7.0 - /Users/saarim/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by dhvector** [comment]
The logic around `useTestInstance` has a bug. The `getUseTestInstance()` returns null and the return type is Boolean, so can't be unboxed in the conditional.

**Comment by gauravpassi** [comment]
any update?

**Comment by tkcarnage** [comment]
+1

**Comment by crafterm** [comment]
We had the same issue with our app and was able to workaround it by specifying the `branchKey` value in the branch.json file - this causes the code that raises (checking the useTestInstance config item to choose between liveKey or testKey) to be skipped.

**Comment by tkcarnage** [comment]
^ yea I did a workaround using the `branchKey` in the branch.json file but it would be nice to get that useTestInstance working again to easily switch between live and test keys without manually changing the branchKey.

**Comment by tkcarnage** [comment]
this thread is a freakin ghost town. Do Branch.io people have devs anymore?
