### ISSUE TITLE
Android crashes on app open with NoSuchMethodError

### ISSUE THREAD

**Issue by LaVielle** [BranchMetrics/react-native-branch-deep-linking-attribution#650]
I just updated from `4.4.0` to `5.0.3` and my android app systematically crashes on open with this error:
```
java.lang.NoSuchMethodError: No static method registerPlugin(Ljava/lang/String;Ljava/lang/String;)V in class Lio/branch/referral/Branch; or its super classes (declaration of 'io.branch.referral.Branch' appears in /data/app/~~fUzA1yHDWTI5-bAcTUlJmw==/com.vytal.vytalconsumerapp.dev-GZhtZNdsgRvKgythSX8kKQ==/base.apk!classes3.dex)
    at io.branch.rnbranch.RNBranchModule.getAutoInstance(RNBranchModule.java:100)
    at com.vytal.vytalconsumerapp.MainApplication.onCreate(MainApplication.java:58)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6754)
    at android.app.ActivityThread.access$1400(ActivityThread.java:244)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7700)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

Here is what `MainApplication.java` looks like:
```Java
package com....;

import android.app.Application;
import android.content.Context;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;

import com.facebook.soloader.SoLoader;

import java.lang.reflect.InvocationTargetException;
import java.util.List;

import com.microsoft.codepush.react.CodePush;

import com.reactnativenavigation.NavigationApplication;
import com.reactnativenavigation.react.NavigationReactNativeHost;
import com.reactnativenavigation.react.ReactGateway;

import io.branch.rnbranch.RNBranchModule;
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;

public class MainApplication extends NavigationApplication {

    private final ReactNativeHost mReactNativeHost =
        new NavigationReactNativeHost(this) {
            @Override
            public boolean getUseDeveloperSupport() {
                return BuildConfig.DEBUG;
            }
            @Override
            protected List<ReactPackage> getPackages() {
                @SuppressWarnings("UnnecessaryLocalVariable")
                List<ReactPackage> packages = new PackageList(this).getPackages();
                // Packages that cannot be autolinked yet can be added manually here, for example:
                return packages;
            }
            @Override
            protected String getJSMainModuleName() {
                return "index";
            }
            @Override
            protected String getJSBundleFile() {
                return CodePush.getJSBundleFile();
            }
        };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }

    @Override
    public void onCreate() {
      super.onCreate();
      RNBranchModule.getAutoInstance(this); // <--------------- error refers to this line...
    }
}
```

and `MainActivity.java`:

```Java
package com.vytal....;

import android.content.Intent;
import com.reactnativenavigation.NavigationActivity;
import io.branch.rnbranch.*;
import com.zoontek.rnbootsplash.RNBootSplash;
import android.os.Bundle;

public class MainActivity extends NavigationActivity {
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
    }

    @Override
    protected void onStart() {
        super.onStart();
        RNBranchModule.initSession(getIntent().getData(), this);
    }

// Commented out because apparently not needed in RNBranch v5
//    @Override
//    protected void onResume() {
//      super.onResume();
//      RNBranchModule.initSession(getIntent().getData(), this);
//    }

    @Override
    public void onNewIntent(Intent intent) {
      super.onNewIntent(intent);
      RNBranchModule.onNewIntent(intent);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);
    }
}
```

`react-native info`:

```
System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 107.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 27, 28, 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_172 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

I'm pretty sure I followed all the install steps correctly. Any idea what the issue might be?

**Comment by echo-branch** [comment]
The error indicates that the build is using an older version of the Branch Android SDK. Try clearing caches to eliminate the possibility that there's an older version laying around somewhere.

**Comment by LaVielle** [comment]
@echo-branch Thanks a lot for the quick reply! Do you have any commands to suggest?
I also suspected a caching issue and tried the following:
```
watchman watch-del-all

rm -rf node_modules
yarn

rm -rf /tmp/metro-bundler-cache-*
rm -rf /tmp/haste-map-react-native-packager-*

./gradlew clean
```
AND restarted my machine before rebuilding...

but still getting the error :(

**Comment by echo-branch** [comment]
Could try removing what gradle has cached. 

```
rm -rf ~/.gradle/caches
```

If that doesn't work, there is a chance the upgrade set conflicting values in the build.gradle. I'd have to do some testing to see if that's possible.

**Comment by LaVielle** [comment]
Hmm... still not working.
also tried `gradle cleanBuildCache` and a few other things suggested here https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache.

Gonna stay on v4.4.0 for now. Please let me know if you find that the upgrade left conflicting value in build.gradle.

**Comment by LaVielle** [comment]
Arg.. I found it!
I had missed some legacy code that had been added in `app/build.gradle` for some unknown reason. Removing the following lines solved the issue:

```diff
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support' &&
          (requested.name != 'multidex' && requested.name != 'multidex-instrumentation')) {
            project.logger.lifecycle(requested.name)
            details.useVersion "${rootProject.ext.supportLibVersion}"
        }
-       if (details.requested.group == 'io.branch.sdk.android') {
-          details.useVersion "3.2.+"
-       }
    }
}
```

This was probably required in an older version of branch, but had not been updated/removed correctly when upgrading.

Sorry for the confusion and thanks for your quick replies!
