### ISSUE TITLE
generateShortUrl crashes Android with react native 68

### ISSUE THREAD

**Issue by fatlinesofcode** [BranchMetrics/react-native-branch-deep-linking-attribution#714]
using the following code
```
const branchUniversalObject = await branch.createBranchUniversalObject(identifier, options)
const linkProperties = {
    feature: 'share'
  }
const controlParams = {
    $desktop_url: url
  }
const response = await branchUniversalObject.generateShortUrl(linkProperties, controlParams)
```

we are see this is crash in android with rn68 (compileSdkVersion = 31), worked fine with rn64 

![Screenshot_20220526-173430_Adore Beauty](https://user-images.githubusercontent.com/505776/170441982-c8f1b991-effb-4529-affe-97d084944d30.jpg)

```
05-27 12:21:35.311  2610  3882 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
05-27 12:21:35.311  2610  3882 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at io.branch.referral.BranchUrlBuilder.<init>(BranchUrlBuilder.java:56)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at io.branch.referral.BranchShortLinkBuilder.<init>(BranchShortLinkBuilder.java:15)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at io.branch.indexing.BranchUniversalObject.getLinkBuilder(BranchUniversalObject.java:699)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at io.branch.indexing.BranchUniversalObject.generateShortUrl(BranchUniversalObject.java:628)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at io.branch.rnbranch.RNBranchModule.generateShortUrl(RNBranchModule.java:630)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
05-27 12:21:35.311  2610  3882 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by fatlinesofcode** [comment]
forgot to update MainActivity.java, works as expected now
