### ISSUE TITLE
Configuration causing android crash

### ISSUE THREAD

**Issue by pilotpirxie** [BranchMetrics/react-native-branch-deep-linking-attribution#786]
### Describe the bug

When I configure Branch following docs it crashes when launching on android:
Logs from ``adb logcat``

```
02-11 12:47:28.853  8387  8387 I flipper : flipper: FlipperClient::addPlugin Inspector
02-11 12:47:28.853  8387  8387 I flipper : flipper: FlipperClient::addPlugin React
02-11 12:47:28.859  8387  8387 I flipper : flipper: FlipperClient::addPlugin Databases
02-11 12:47:28.863  8387  8387 I flipper : flipper: FlipperClient::addPlugin Preferences
02-11 12:47:28.863  8387  8387 I flipper : flipper: FlipperClient::addPlugin CrashReporter
02-11 12:47:28.867  8387  8387 I flipper : flipper: FlipperClient::addPlugin Network
02-11 12:47:28.884  8387  8387 I BranchSDK: !SDK-VERSION-STRING!:io.branch.sdk.android:library:5.2.7
02-11 12:47:28.886  8387  8387 E pl.testapp.testapp: Invalid ID 0x00000000.
02-11 12:47:28.887  8387  8387 E pl.testapp.testapp: Invalid ID 0x00000000.
02-11 12:47:28.887  8387  8387 D AndroidRuntime: Shutting down VM
02-11 12:47:28.887  8387  8458 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
02-11 12:47:28.887  8387  8458 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
02-11 12:47:28.887  8387  8458 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
02-11 12:47:28.889  8387  8387 E AndroidRuntime: FATAL EXCEPTION: main
02-11 12:47:28.889  8387  8387 E AndroidRuntime: Process: pl.testapp.testapp, PID: 8387
02-11 12:47:28.889  8387  8387 E AndroidRuntime: java.lang.RuntimeException: Unable to create application pl.testapp.testapp.MainApplication: android.content.res.Resources$NotFoundException: String resource ID #0x0
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-11 12:47:28.889  8387  8387 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at android.content.res.Resources.getText(Resources.java:444)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at android.content.res.Resources.getString(Resources.java:537)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at io.branch.referral.BranchUtil.readBranchKey(BranchUtil.java:109)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at io.branch.referral.Branch.getAutoInstance(Branch.java:486)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at io.branch.rnbranch.RNBranchModule.getAutoInstance(RNBranchModule.java:106)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at pl.testapp.testapp.MainApplication.onCreate(MainApplication.java:63)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
02-11 12:47:28.889  8387  8387 E AndroidRuntime:        ... 8 more
02-11 12:47:28.906   320   374 D goldfish-address-space: claimShared: Ask to claim region [0x3f71ad000 0x3f76bd000]
02-11 12:47:28.924   517   555 D EventSequenceValidator: Transition from ACTIVITY_LAUNCHED to ACTIVITY_CANCELLED
02-11 12:47:28.958  8387  8387 I Process : Sending signal. PID: 8387 SIG: 9
02-11 12:47:29.024   300   300 I Zygote  : Process 8387 exited due to signal 9 (Killed)
```

### Steps to reproduce

1. Create a new bare react native project with React Native 0.69.7
2. Install ``react-native-branch``
3. Add ``branch.json`` file
4. Modify AppDelegate like in the docs: https://help.branch.io/developers-hub/docs/react-native#ios-1
5. Modify MainApplication and MainActivity like in the docs https://help.branch.io/developers-hub/docs/react-native#android-1
6. Run ``yarn android``
7. App will crash

```java
// MainApplication.java
package pl.testapp.testapp;

import android.app.Application;
import android.content.Context;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.config.ReactFeatureFlags;
import com.facebook.soloader.SoLoader;
import pl.testapp.testapp.newarchitecture.MainApplicationReactNativeHost;
import java.lang.reflect.InvocationTargetException;
import java.util.List;
import io.branch.rnbranch.RNBranchModule;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };

  private final ReactNativeHost mNewArchitectureNativeHost =
      new MainApplicationReactNativeHost(this);

  @Override
  public ReactNativeHost getReactNativeHost() {
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      return mNewArchitectureNativeHost;
    } else {
      return mReactNativeHost;
    }
  }

  @Override
  public void onCreate() {
    super.onCreate();
    // If you opted-in for the New Architecture, we enable the TurboModule system
    ReactFeatureFlags.useTurboModules = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());

      // Branch logging for debugging
      RNBranchModule.enableLogging();
      RNBranchModule.getAutoInstance(this);
  }

  /**
   * Loads Flipper in React Native templates. Call this in the onCreate method with something like
   * initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
   *
   * @param context
   * @param reactInstanceManager
   */
  private static void initializeFlipper(
      Context context, ReactInstanceManager reactInstanceManager) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         We use reflection here to pick up the class that initializes Flipper,
        since Flipper library is not available in release mode
        */
        Class<?> aClass = Class.forName("pl.testapp.testapp.ReactNativeFlipper");
        aClass
            .getMethod("initializeFlipper", Context.class, ReactInstanceManager.class)
            .invoke(null, context, reactInstanceManager);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }
}

```

```java
// MainActivity.java
package pl.testapp.testapp;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;

import android.os.Bundle;
import org.devio.rn.splashscreen.SplashScreen;
import io.branch.rnbranch.*;
import android.content.Intent;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "testapp";
  }

  // Override onStart:
  @Override
  protected void onStart() {
    super.onStart();
    RNBranchModule.initSession(getIntent().getData(), this);
  }

  // Override onNewIntent:
  @Override
  public void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    RNBranchModule.onNewIntent(intent);
  }

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    SplashScreen.show(this);  // here
    super.onCreate(savedInstanceState);
  }

  /**
   * Returns the instance of the {@link ReactActivityDelegate}. There the RootView is created and
   * you can specify the renderer you wish to use - the new renderer (Fabric) or the old renderer
   * (Paper).
   */
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new MainActivityDelegate(this, getMainComponentName());
  }

  public static class MainActivityDelegate extends ReactActivityDelegate {
    public MainActivityDelegate(ReactActivity activity, String mainComponentName) {
      super(activity, mainComponentName);
    }

    @Override
    protected ReactRootView createRootView() {
      ReactRootView reactRootView = new ReactRootView(getContext());
      // If you opted-in for the New Architecture, we enable the Fabric Renderer.
      reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);
      return reactRootView;
    }

    @Override
    protected boolean isConcurrentRootEnabled() {
      // If you opted-in for the New Architecture, we enable Concurrent Root (i.e. React 18).
      // More on this on https://reactjs.org/blog/2022/03/29/react-v18.html
      return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
    }
  }
}

```

package.json
```json
{
  "name": "testapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "lint": "./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx",
    "lint:fix": "eslint --fix --ext .js,.jsx,.ts,.tsx .",
    "build:android": "cd android && ./gradlew bundleRelease && cd .. && open ./android/app/build/outputs/bundle/release"
  },
  "dependencies": {
    "@invertase/react-native-apple-authentication": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-clipboard/clipboard": "^1.11.0",
    "@react-native-community/netinfo": "^9.3.0",
    "@react-native-firebase/analytics": "^16.5.1",
    "@react-native-firebase/app": "^16.5.1",
    "@react-native-masked-view/masked-view": "^0.2.7",
    "@react-navigation/elements": "^1.3.14",
    "@react-navigation/native": "^6.1.3",
    "@react-navigation/stack": "^6.3.12",
    "@redux-devtools/extension": "^3.2.5",
    "@sentry/react-native": "5.0.0-alpha.10",
    "axios": "^1.3.2",
    "dayjs": "^1.11.5",
    "eslint-plugin-jest": "^27.2.1",
    "jest": "^29.4.2",
    "prettier": "^2.8.3",
    "react": "18.2.0",
    "react-native": "0.69.7",
    "react-native-branch": "^5.7.0",
    "react-native-device-info": "^10.3.0",
    "react-native-fbsdk-next": "^11.1.0",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-onesignal": "^4.4.1",
    "react-native-permissions": "^3.6.1",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.19.0",
    "react-native-splash-screen": "^3.3.0",
    "react-redux": "^8.0.2",
    "redux": "^4.2.1",
    "redux-saga": "^1.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.20.13",
    "@react-native-community/eslint-config": "^3.1.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.4.0",
    "@types/react": "^18.0.27",
    "@types/react-native": "^0.69.5",
    "@types/react-redux": "^7.1.24",
    "@typescript-eslint/eslint-plugin": "^5.51.0",
    "@typescript-eslint/parser": "^5.51.0",
    "eslint": "8.33.0",
    "metro-react-native-babel-preset": "^0.73.3",
    "typescript": "^4.9.5"
  }
}
```

branch.json
```json
{
    "debugMode": true,
    "liveKey": "HERE IS PROPER KEY, REMOVED FOR ISSUE PURPOSE",
    "testKey": "HERE IS PROPER KEY, REMOVED FOR ISSUE PURPOSE",
    "useTestInstance": false,
    "delayInitToCheckForSearchAds": true,
    "enableFacebookLinkCheck": true
}
```

### Expected behavior

Run app without crash

### SDK Version

5.7.0

### Make and Model

Nexus 5 AVD

### OS

Android 10

**Comment by raazatul7** [comment]
Hi, any update on this?
having the same issue!

**Comment by gdeluna-branch** [comment]
I'll take a look at this.

**Comment by gdeluna-branch** [comment]
@pilotpirxie, @raazatul7 Can you confirm the placement of your `branch.json`? I get the expected keys when I place `branch.json` in `app/src/main/assets/` 

Do these instructions help? https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/blob/master/docs/branch.json.md#manual-integration-without-react-native-link

I've repro'd that if you aren't using `react-native link` and if you don't have the keys in your `AndroidManifest.xml` it will throw that exception.

**Comment by gdeluna-branch** [comment]
Please reopen if this persists.

Thanks

**Comment by JimTeva** [comment]
Ok the solution was: 

1. Create a file named branch.json
```json
{
  "debugMode": true,
  "liveKey": "key_live_xxxx",
  "testKey": "key_test_yyyy",
  "useTestInstance": true,
  "enableFacebookLinkCheck": true
}
```

2. Put branch.json file in folder app/src/main/assets/

**Comment by enzzoperez** [comment]
> Ok the solution was:
> 
> 1. Create a file named branch.json
> 
> ```json
> {
>   "debugMode": true,
>   "liveKey": "key_live_xxxx",
>   "testKey": "key_test_yyyy",
>   "useTestInstance": true,
>   "enableFacebookLinkCheck": true
> }
> ```
> 
> 2. Put branch.json file in folder app/src/main/assets/

thanks, this worked for me.. Im in v5.8.0, the line `RNBranchModule.getAutoInstance(this);` caused problems
